### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by msackman** [glycerine/go-capnproto#28]
Hi,

It would be very useful if the docs for all the API functions which take optional buffers made it clear whether or not the buffer may still be used once the function returns.

For example, from my reading of ReadFromStream, the buf that you can provide to it will contain data that is reachable from the segments returned. So if you have a tight loop reading segments off a socket and pushing those segments down a channel (of capacity > 0) then it's not safe to reuse the buf - the next call to ReadFromStream will start and reset the buf before the segment has been processed at the other end of the channel.

Is my reading of this code correct, and could you possibly add suitable notes to the docs? Many thanks.

**Comment by glycerine** [comment]
@msackman Hi Matt,
Hmm, that's an interesting observation. I looked over ReadFromStream and indeed it does seem to have the problem you suggest. I haven't touched this particular function since I inherited the code base, but it does look like a copy at these two lines
~~~
https://github.com/glycerine/go-capnproto/blob/master/mem.go#L140
https://github.com/glycerine/go-capnproto/blob/master/mem.go#L141
//currently:
hdrv := buf.Bytes()[4 : hdrsz+4]
datav := buf.Bytes()[hdrsz+4:]

// I'm thinking this might fix the issue
hdrv := make([]byte, hdrsz); copy(hdrv, buf.Bytes()[4 : hdrsz+4])
datav := make([]byte, len(buf)-(hdrsz+4)); copy(datav, buf.Bytes()[hdrsz+4:])
~~~

I'm in a bit of a crunch right now so I can't do much more than offer this suggestion just now.

Would you mind writing a test that detects the situation and/or seeing if the above suggestion fixes the issue?

**Comment by msackman** [comment]
Hi Jason,

No problem that you're swamped - these things are hardly stopping me from work.

It's not necessarily a problem - I've come across other libraries that do the same thing; you could easily argue that knowing that the decoding is not causing lots and lots of copying to go on is a benefit. The consequence is that you must not reuse/reset those bufs until after you're done with the segment. That's just fine. It's more just about making sure that sort of thing is documented and understood by users - it's really part of the API.

Some quick testing suggests that this is as thought - changing code to:

    buf := &bytes.Buffer{}
    seg, err := capn.ReadFromStream(socket, buf)
    fmt.Println(seg)
    l := buf.Len()
    buf.Reset()
    buf.Grow(l + 1)
    buf.Write(make([]byte, l))
    fmt.Println(seg)

does indeed show the segment has changed.

**Comment by glycerine** [comment]
added a warning in f92ec2cf8f9de231e9232d21cded9bca9f01cb75
