### ISSUE TITLE
make shows can't find the path

### ISSUE THREAD

**Issue by jjjjilyf** [glycerine/go-capnproto#38]
Hello there.I followed the getting start steps and when I run make,it shows.
H:\MqantServer\src\github.com\glycerine\go-capnproto>mingw32-make
cd capnpc-go; go install && go build
系统找不到指定的路径(English is:system can't find the specified path)。
Makefile:4: recipe for target 'prepare' failed
mingw32-make: *** [prepare] Error 1.

Expect your reply.

**Comment by glycerine** [comment]
Get a software developer friend to help you out.  Makefiles from unix won't typically work on windows. You can try under a cygwin shell, but you'll probably just need to manually enter the commands one at a time from the makefile, translating each one into its windows version.  Forward slashes need to be become backslashes, %PATH% for capnpc and capnpc-go need to be right.

> Expect your reply.

Comes across as very impolite. Since you're not a native English speaker, a tip: Don't say that again to anyone else.

Good luck, Jim.
